export const ADMIN_API = {
    GET_BADGE:'/admin/badges/',
    ADD_BADGE:'/admin/badges/',
    EDIT_BADGE:'/admin/badges/',
    LIST_BADGE:'/admin/list-badge/',
    UNLIST_BADGE:'/admin/unlist-badge/',
    COIN_PLANS:'/admin/coin-plans',
    GET_USER_REPORT:'/admin/reports/users',
    BAN_USER_REPORT:'/admin/reports/ban-user',
    REJECT_USER_REPORT:'/admin/reports/reject',
    REJECT_ALL_USER_REPORT:'/admin/reports/reject-all',
    WARNING_USER_REPORT:'/admin/reports/warning',
    GET_TAG: "/admin/tags",
    ADD_TAG: "/admin/tags",
    EDIT_TAG: "/admin/tags",
    LIST_TAG: "/admin/tags/list",
    UNLIST_TAG: "/admin/tags/unlist",
    REWARD_ADD: '/admin/reward/add',
    REWARD_EDIT: '/admin/reward/edit',
    REWARD_LIST: '/admin/reward/list',
    REWARD_UNLIST: '/admin/reward/unlist',
    REWARD_GET_ALL: '/admin/reward/get-all',
    REWARD_GET_ONE: '/admin/reward/get-one',
    GET_ORDERS: "/admin/order",
    GET_ORDER: "/admin/order",
}