export const USER_API = {
    GET_BADGES:'/badges',
    GET_USER_BADGES:'/user-badges',
    UNLOCK_BADGE:'badges/unlock',
    SET_CURRENT_BADGE:'/badges/set-current',
    EDIT_PROFILE:'/user/update-profile',
    CHANGE_PASSWORD:'/user/change-password',
    CHECK_PASSWORD_STATUS:'/user/has-password',
    GET_COIN_PLANS:'/Gcoin',
    GCOIN_CHECKOUT:'/Gcoin/checkout',
    GCOIN_PAYMENT_SUCCESS: '/Gcoin/success',
    GCOIN_TRANSACTION: '/Gcoin/transaction-history',
    CHECK_TITLE:'/questions/check-title',
    CHECK_SIMILAR: '/questions/find-similar',
    FETCH_QUESTIONS: '/questions/get-all',
    FETCH_ONE_BY_SLUG:'/questions/get-one',
    RELATED_QUESTIONS:'/questions/get-related',
    REACT_TO_QUESTION:'/questions/react',
    HAS_UNREAD_NOTIFICATION: '/notification/has-unread',
    MARK_ALL_AS_READ: '/notification/mark-all-read',
    FETCH_NOTIFICATION: '/notification/get-all',
    SEARCH_TAGS: '/tag/search-tags',
    GET_TOP_TAGS:'/tag/get-top',
    ADD_ANSWER: '/answer/add',
    CAN_USER_ANSWER: '/answer/can-answer',
    LIST_ANSWER: '/answer/list',
    ANSWER_REACT: '/answer/react',
    ANSWER_UPDATE_QUALITY: '/answer/update-quality',
}